# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(960, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 631))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab{width:200;height:50;}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_query = QtWidgets.QWidget()
        self.tab_query.setObjectName("tab_query")
        self.widget_query = QtWidgets.QWidget(self.tab_query)
        self.widget_query.setGeometry(QtCore.QRect(0, 0, 1000, 51))
        self.widget_query.setStyleSheet("QWidget#widget_query{background-color: rgb(212, 212, 212);}")
        self.widget_query.setObjectName("widget_query")
        self.label_4 = QtWidgets.QLabel(self.widget_query)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 60, 30))
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit.setGeometry(QtCore.QRect(80, 10, 104, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.widget_query)
        self.label_5.setGeometry(QtCore.QRect(210, 10, 60, 30))
        self.label_5.setObjectName("label_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_2.setGeometry(QtCore.QRect(270, 10, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_6 = QtWidgets.QLabel(self.widget_query)
        self.label_6.setGeometry(QtCore.QRect(400, 10, 60, 30))
        self.label_6.setObjectName("label_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_3.setGeometry(QtCore.QRect(460, 10, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_query)
        self.pushButton.setGeometry(QtCore.QRect(660, 10, 91, 30))
        self.pushButton.setObjectName("pushButton")
        self.widget_checkBox = QtWidgets.QWidget(self.tab_query)
        self.widget_checkBox.setGeometry(QtCore.QRect(0, 50, 1000, 35))
        self.widget_checkBox.setAutoFillBackground(False)
        self.widget_checkBox.setStyleSheet("QWidget#widget_checkBox{background-color: rgb(212, 212, 212);}")
        self.widget_checkBox.setObjectName("widget_checkBox")
        self.checkBox_T = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_T.setGeometry(QtCore.QRect(580, 10, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_T.setFont(font)
        self.checkBox_T.setObjectName("checkBox_T")
        self.checkBox_K = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_K.setGeometry(QtCore.QRect(740, 10, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_K.setFont(font)
        self.checkBox_K.setObjectName("checkBox_K")
        self.checkBox_Z = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_Z.setGeometry(QtCore.QRect(420, 10, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Z.setFont(font)
        self.checkBox_Z.setObjectName("checkBox_Z")
        self.checkBox_D = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_D.setGeometry(QtCore.QRect(260, 10, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_D.setFont(font)
        self.checkBox_D.setObjectName("checkBox_D")
        self.checkBox_G = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_G.setGeometry(QtCore.QRect(100, 10, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_G.setFont(font)
        self.checkBox_G.setObjectName("checkBox_G")
        self.label_type_2 = QtWidgets.QLabel(self.widget_checkBox)
        self.label_type_2.setGeometry(QtCore.QRect(20, 10, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_type_2.setFont(font)
        self.label_type_2.setObjectName("label_type_2")
        self.tableView = QtWidgets.QTableView(self.tab_query)
        self.tableView.setGeometry(QtCore.QRect(0, 114, 1000, 391))
        self.tableView.setObjectName("tableView")
        self.widget_save = QtWidgets.QWidget(self.tab_query)
        self.widget_save.setGeometry(QtCore.QRect(0, 500, 1000, 50))
        self.widget_save.setStyleSheet("QWidget#widget_save{background-color: rgb(212, 212, 212);}")
        self.widget_save.setObjectName("widget_save")
        self.pushButton_saveall = QtWidgets.QPushButton(self.widget_save)
        self.pushButton_saveall.setGeometry(QtCore.QRect(10, 10, 120, 30))
        self.pushButton_saveall.setObjectName("pushButton_saveall")
        self.pushButton_save = QtWidgets.QPushButton(self.widget_save)
        self.pushButton_save.setGeometry(QtCore.QRect(890, 10, 90, 30))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label = QtWidgets.QLabel(self.tab_query)
        self.label.setGeometry(QtCore.QRect(0, 80, 1001, 37))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(:/png/table_img.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_query, "")
        self.tab_price = QtWidgets.QWidget()
        self.tab_price.setObjectName("tab_price")
        self.widget_price = QtWidgets.QWidget(self.tab_price)
        self.widget_price.setGeometry(QtCore.QRect(0, 0, 1000, 50))
        self.widget_price.setStyleSheet("QWidget#widget_price{background-color: rgb(212, 212, 212);}")
        self.widget_price.setObjectName("widget_price")
        self.label_from = QtWidgets.QLabel(self.widget_price)
        self.label_from.setGeometry(QtCore.QRect(20, 10, 60, 30))
        self.label_from.setObjectName("label_from")
        self.textEdit_from = QtWidgets.QTextEdit(self.widget_price)
        self.textEdit_from.setGeometry(QtCore.QRect(80, 10, 104, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_from.setFont(font)
        self.textEdit_from.setObjectName("textEdit_from")
        self.label_to = QtWidgets.QLabel(self.widget_price)
        self.label_to.setGeometry(QtCore.QRect(210, 10, 60, 30))
        self.label_to.setObjectName("label_to")
        self.textEdit_to = QtWidgets.QTextEdit(self.widget_price)
        self.textEdit_to.setGeometry(QtCore.QRect(270, 10, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_to.setFont(font)
        self.textEdit_to.setObjectName("textEdit_to")
        self.label_date = QtWidgets.QLabel(self.widget_price)
        self.label_date.setGeometry(QtCore.QRect(400, 10, 60, 30))
        self.label_date.setObjectName("label_date")
        self.textEdit_date = QtWidgets.QTextEdit(self.widget_price)
        self.textEdit_date.setGeometry(QtCore.QRect(460, 10, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_date.setFont(font)
        self.textEdit_date.setObjectName("textEdit_date")
        self.pushButton_price = QtWidgets.QPushButton(self.widget_price)
        self.pushButton_price.setGeometry(QtCore.QRect(660, 10, 91, 30))
        self.pushButton_price.setObjectName("pushButton_price")
        self.tableView_2 = QtWidgets.QTableView(self.tab_price)
        self.tableView_2.setGeometry(QtCore.QRect(0, 50, 1001, 451))
        self.tableView_2.setObjectName("tableView_2")
        self.widget_save2 = QtWidgets.QWidget(self.tab_price)
        self.widget_save2.setGeometry(QtCore.QRect(0, 500, 1000, 50))
        self.widget_save2.setStyleSheet("QWidget#widget_save2{background-color: rgb(212, 212, 212);}\n"
"")
        self.widget_save2.setObjectName("widget_save2")
        self.pushButton_saveall2 = QtWidgets.QPushButton(self.widget_save2)
        self.pushButton_saveall2.setGeometry(QtCore.QRect(10, 10, 120, 30))
        self.pushButton_saveall2.setObjectName("pushButton_saveall2")
        self.pushButton_save2 = QtWidgets.QPushButton(self.widget_save2)
        self.pushButton_save2.setGeometry(QtCore.QRect(890, 10, 90, 30))
        self.pushButton_save2.setObjectName("pushButton_save2")
        self.tabWidget.addTab(self.tab_price, "")
        self.tab_qiangpiao = QtWidgets.QWidget()
        self.tab_qiangpiao.setObjectName("tab_qiangpiao")
        self.widget = QtWidgets.QWidget(self.tab_qiangpiao)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1000, 550))
        self.widget.setObjectName("widget")
        self.lineEdit_Username = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Username.setGeometry(QtCore.QRect(200, 70, 600, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lineEdit_Username.setFont(font)
        self.lineEdit_Username.setText("")
        self.lineEdit_Username.setMaxLength(20)
        self.lineEdit_Username.setCursorPosition(0)
        self.lineEdit_Username.setClearButtonEnabled(True)
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(200, 150, 600, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setText("")
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setCursorPosition(0)
        self.lineEdit_Password.setDragEnabled(False)
        self.lineEdit_Password.setClearButtonEnabled(True)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.textEdit_fromstation = QtWidgets.QTextEdit(self.widget)
        self.textEdit_fromstation.setGeometry(QtCore.QRect(200, 230, 100, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.textEdit_fromstation.setFont(font)
        self.textEdit_fromstation.setObjectName("textEdit_fromstation")
        self.textEdit_trainnum = QtWidgets.QTextEdit(self.widget)
        self.textEdit_trainnum.setGeometry(QtCore.QRect(590, 230, 100, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.textEdit_trainnum.setFont(font)
        self.textEdit_trainnum.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textEdit_trainnum.setObjectName("textEdit_trainnum")
        self.textEdit_tostation = QtWidgets.QTextEdit(self.widget)
        self.textEdit_tostation.setGeometry(QtCore.QRect(325, 230, 100, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.textEdit_tostation.setFont(font)
        self.textEdit_tostation.setObjectName("textEdit_tostation")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(700, 230, 100, 35))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_qiangpiao = QtWidgets.QPushButton(self.widget)
        self.pushButton_qiangpiao.setGeometry(QtCore.QRect(200, 330, 600, 35))
        self.pushButton_qiangpiao.setObjectName("pushButton_qiangpiao")
        self.textEdit_traindate = QtWidgets.QTextEdit(self.widget)
        self.textEdit_traindate.setGeometry(QtCore.QRect(440, 230, 131, 35))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.textEdit_traindate.setFont(font)
        self.textEdit_traindate.setObjectName("textEdit_traindate")
        self.tabWidget.addTab(self.tab_qiangpiao, "")
        self.tab_analysis = QtWidgets.QWidget()
        self.tab_analysis.setObjectName("tab_analysis")
        self.widget_query_2 = QtWidgets.QWidget(self.tab_analysis)
        self.widget_query_2.setGeometry(QtCore.QRect(0, 0, 1000, 51))
        self.widget_query_2.setStyleSheet("QWidget#widget_query{background-color: rgb(212, 212, 212);}")
        self.widget_query_2.setObjectName("widget_query_2")
        self.label_7 = QtWidgets.QLabel(self.widget_query_2)
        self.label_7.setGeometry(QtCore.QRect(70, 10, 60, 30))
        self.label_7.setObjectName("label_7")
        self.textEdit_analysis_from = QtWidgets.QTextEdit(self.widget_query_2)
        self.textEdit_analysis_from.setGeometry(QtCore.QRect(130, 10, 104, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_analysis_from.setFont(font)
        self.textEdit_analysis_from.setObjectName("textEdit_analysis_from")
        self.label_8 = QtWidgets.QLabel(self.widget_query_2)
        self.label_8.setGeometry(QtCore.QRect(260, 10, 60, 30))
        self.label_8.setObjectName("label_8")
        self.textEdit_analysis_to = QtWidgets.QTextEdit(self.widget_query_2)
        self.textEdit_analysis_to.setGeometry(QtCore.QRect(320, 10, 104, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_analysis_to.setFont(font)
        self.textEdit_analysis_to.setObjectName("textEdit_analysis_to")
        self.pushButton_analysis_query = QtWidgets.QPushButton(self.widget_query_2)
        self.pushButton_analysis_query.setGeometry(QtCore.QRect(460, 10, 90, 30))
        self.pushButton_analysis_query.setObjectName("pushButton_analysis_query")
        self.label_16 = QtWidgets.QLabel(self.widget_query_2)
        self.label_16.setGeometry(QtCore.QRect(740, 20, 20, 20))
        self.label_16.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.widget_query_2)
        self.label_18.setGeometry(QtCore.QRect(820, 20, 20, 20))
        self.label_18.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_14 = QtWidgets.QLabel(self.widget_query_2)
        self.label_14.setGeometry(QtCore.QRect(630, 20, 20, 20))
        self.label_14.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(self.widget_query_2)
        self.label_19.setGeometry(QtCore.QRect(850, 20, 51, 20))
        self.label_19.setObjectName("label_19")
        self.label_15 = QtWidgets.QLabel(self.widget_query_2)
        self.label_15.setGeometry(QtCore.QRect(650, 20, 81, 20))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.widget_query_2)
        self.label_17.setGeometry(QtCore.QRect(750, 20, 60, 20))
        self.label_17.setObjectName("label_17")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_analysis)
        self.tableWidget.setGeometry(QtCore.QRect(0, 50, 1000, 241))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView{font:16pt \'楷体\';};\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(11)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_analysis)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 290, 1000, 255))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 998, 253))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 991, 251))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.tab_analysis, "")
        self.tab_time = QtWidgets.QWidget()
        self.tab_time.setObjectName("tab_time")
        self.widget_time = QtWidgets.QWidget(self.tab_time)
        self.widget_time.setGeometry(QtCore.QRect(0, 0, 1000, 551))
        self.widget_time.setStyleSheet("QWidget#widget_time{background-image: url(:/png/time_bg.png);}")
        self.widget_time.setObjectName("widget_time")
        self.label_time_text = QtWidgets.QLabel(self.widget_time)
        self.label_time_text.setGeometry(QtCore.QRect(10, 160, 80, 30))
        self.label_time_text.setObjectName("label_time_text")
        self.lineEdit_station = QtWidgets.QLineEdit(self.widget_time)
        self.lineEdit_station.setGeometry(QtCore.QRect(90, 160, 113, 30))
        self.lineEdit_station.setObjectName("lineEdit_station")
        self.pushButton_time_query = QtWidgets.QPushButton(self.widget_time)
        self.pushButton_time_query.setGeometry(QtCore.QRect(250, 160, 75, 30))
        self.pushButton_time_query.setObjectName("pushButton_time_query")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_time)
        self.scrollArea.setGeometry(QtCore.QRect(0, 200, 1001, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 999, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 991, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_time, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "火车票分析助手"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">出发地:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">目的地:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">出发日:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.checkBox_T.setText(_translate("MainWindow", "T-特快"))
        self.checkBox_K.setText(_translate("MainWindow", "K-快速"))
        self.checkBox_Z.setText(_translate("MainWindow", "Z-直达"))
        self.checkBox_D.setText(_translate("MainWindow", "D-动车"))
        self.checkBox_G.setText(_translate("MainWindow", "GC-高铁"))
        self.label_type_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">车次类型:</p></body></html>"))
        self.pushButton_saveall.setText(_translate("MainWindow", "保存至所有数据"))
        self.pushButton_save.setText(_translate("MainWindow", "单个保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_query), _translate("MainWindow", "车票查询"))
        self.label_from.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">出发地:</span></p></body></html>"))
        self.label_to.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">目的地:</span></p></body></html>"))
        self.label_date.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">出发日:</span></p></body></html>"))
        self.pushButton_price.setText(_translate("MainWindow", "查询"))
        self.pushButton_saveall2.setText(_translate("MainWindow", "保存至所有数据"))
        self.pushButton_save2.setText(_translate("MainWindow", "单个保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_price), _translate("MainWindow", "票价查询"))
        self.lineEdit_Username.setPlaceholderText(_translate("MainWindow", "请输入账号"))
        self.lineEdit_Password.setPlaceholderText(_translate("MainWindow", "请输入账号密码"))
        self.comboBox.setItemText(0, _translate("MainWindow", "特等座"))
        self.comboBox.setItemText(1, _translate("MainWindow", "商务座"))
        self.comboBox.setItemText(2, _translate("MainWindow", "一等座"))
        self.comboBox.setItemText(3, _translate("MainWindow", "二等座"))
        self.comboBox.setItemText(4, _translate("MainWindow", "高级软卧"))
        self.comboBox.setItemText(5, _translate("MainWindow", "软卧"))
        self.comboBox.setItemText(6, _translate("MainWindow", "硬卧"))
        self.comboBox.setItemText(7, _translate("MainWindow", "软座"))
        self.comboBox.setItemText(8, _translate("MainWindow", "硬座"))
        self.pushButton_qiangpiao.setText(_translate("MainWindow", "抢票"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_qiangpiao), _translate("MainWindow", "抢票"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">出发地:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">目的地:</span></p></body></html>"))
        self.pushButton_analysis_query.setText(_translate("MainWindow", "查询"))
        self.label_19.setText(_translate("MainWindow", "不紧张"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">非常紧张</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">紧张</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "车次"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "出发站"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "到达站"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "出发时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "到达时间"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "历时"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "第二天"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "第三天"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "第四天"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "第五天"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "第六天"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_analysis), _translate("MainWindow", "卧铺售票分析"))
        self.label_time_text.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">起售车站:</span></p></body></html>"))
        self.pushButton_time_query.setText(_translate("MainWindow", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_time), _translate("MainWindow", "车票起售时间"))
import img_rc
